# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vladimir Rozhkov
email: xpunkerx@gmail.com
description: Software Engineer, Tech Lead, People Manager
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rozhkov.me" # the base hostname & protocol for your site
github_username:  rozhok

# Build settings
markdown: kramdown
