author = "Vladimir Rozhkov"
baseurl = "https://www.rozhkov.me/"
canonifyurls = true
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/xrozhokx\" target=\"_blank\">Twitter</a>"
paginate = 3
theme = "alageek"
title = "Vladimir Rozhkov"
DisqusShortname = "rozhkov"

[params]
copyright = "© 2018 by Vladimir Rozhkov"
copyrightUrl = "https://www.rozhkov.me/"
faviconfile = "https://www.rozhkov.me/favicon.ico"
latestpostcount = 5
logofile = "https://www.rozhkov.me/favicon.ico"
highlightjs = true
ga = "UA-86260054-1"

#[[params.best_posts]]
#title = "Migrate to Hugo from Jekyll"
#url = "/blog/migrate-from-jekyll/"

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.primary]]
identifier = "cv"
name = "CV"
url = "/cv/"
weight = 20

[[menu.secondary]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/xrozhokx"
weight = 110

[[menu.secondary]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/full_of_hatred"
weight = 120
